### ISSUE TITLE
ogonek glyphs not joined in v3.000

### ISSUE THREAD

**Issue by m4rc1e** [itfoundry/Poppins#10]
This occurs in most weights

![screen shot 2017-08-11 at 10 55 41](https://user-images.githubusercontent.com/7525512/29208927-fa0e1a10-7e83-11e7-909c-a490665faadf.png)
![screen shot 2017-08-11 at 10 55 30](https://user-images.githubusercontent.com/7525512/29208928-fa0e48e6-7e83-11e7-833b-d0b3d5022031.png)

**Comment by lianghai** [comment]
For now I've applied minimal changes to `Eogonek`, `Iogonek`, `aogonek`, `iogonek`, and `uogonek`, so the ogonek part is not detached.
Will redesign ogonek-involving glyphs for the next release.

**Comment by m4rc1e** [comment]
Thank you!
