### ISSUE TITLE
Rendering of 'e' in Mac OS 10

### ISSUE THREAD

**Issue by m4rc1e** [itfoundry/Poppins#16]
Rather strangely, in v3.100, OS 10.12.4 renders the 'e' pretty badly. This is strange because Mac Os does its own thing for rendering fonts. As far as I am aware, it ignores hinting information.

![screen shot 2017-10-09 at 11 33 37](https://user-images.githubusercontent.com/7525512/31334344-d8327efa-ace5-11e7-9d86-7b987d6d92a9.png)

The bar is way too thin. However, in the outlines, it seems fine.

![screen shot 2017-10-09 at 11 35 34](https://user-images.githubusercontent.com/7525512/31334355-e7813e3c-ace5-11e7-9f6d-292519fed0b9.png)
*glyphsapp*

cc @davelab6

**Comment by davelab6** [comment]
Do you have it installed? , That looks just like the old version that the lastest release had fixed

**Comment by m4rc1e** [comment]
@davelab6 I don't have it installed. It is very strange, yes it renders the same as the old but I am intrigued as to why it is so different from the outline.

**Comment by davelab6** [comment]
@satyarajpurohit @lianghai I can't release the update until this is fixed. Please take a look :)

**Comment by satyarajpurohit** [comment]
Hi @lianghai Can you check this?

**Comment by m4rc1e** [comment]
Its fixed
![desktop_os_x_el_capitan_safari_9 1_](https://user-images.githubusercontent.com/7525512/33269197-bce2608a-d377-11e7-9514-fa6de58161a1.gif)
