### ISSUE TITLE
Still problem with "t" with accute

### ISSUE THREAD

**Issue by martinler** [itfoundry/poppins#3]
Hello, unfortunately there is still issue with your font Poppins and with character "t" with accute. Last year you mentioned that you will upload new version of your font file, but no new files so far. Please, can you let me know, if we can get this new correct font file.

Thank you!

**Comment by pankevely** [comment]
I have to back martinler on this one – this completely obliterates the usefulness of the font family in almost any Slavic language; and there's quite [a few] (https://en.wikipedia.org/wiki/Slavic_languages#/media/File:Slavic_languages_in_the_World.PNG).

Shame such a small mistake stays unchecked for so long.

**Comment by majlan** [comment]
Yep, makes it impossible to use this font in a lot of languages (you can't quite avoid using this letter even though it's not used much often).

**Comment by lianghai** [comment]
Fixed in the latest release 2.100: https://github.com/itfoundry/poppins/releases/tag/v2.100
