### ISSUE TITLE
Difference between Google Fonts and others fonts directories

### ISSUE THREAD

**Issue by borisdamevin** [itfoundry/Poppins#36]
Hi @rahulgajjar ,

On Google Fonts, Poppins has one styles, but on Adode or Font Squirrel, glyphs are different (ex. coma).

Each style is good?

Thank you.

**Comment by satyarajpurohit** [comment]
Dear @borisdamevin, 

The fonts hosted on GoogleFonts are outdated and has several issues. Please download the latest fonts from our GitHub or from our website: http://indiantypefoundry.com/fonts/poppins 

Best, Satya

**Comment by borisdamevin** [comment]
Thank you for this anwser.

Why do not update version on Google Font ?

**Comment by ianferrell** [comment]
Hopefully it can be updated on Google. I am looking forward to the rounded dot glyph/period being included on Google.

**Comment by satyarajpurohit** [comment]
Hi,

The latest files can be downloaded from our website here:
https://www.indiantypefoundry.com/fonts/poppins

I hope Google update these fonts soon.

Best regards,
Satya


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Indian Type Foundry
Original, quality fonts for India and the Global World
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
