### ISSUE TITLE
Woff Format

### ISSUE THREAD

**Issue by borisdamevin** [itfoundry/Poppins#37]
Hi, 

I tried a lot of converter for get `.woff` and `.woff2` files from `.otf`, but each one generated don't display the same render compared to `.otf` format, but on your website, your `.woff` file seem display the good render.

What you use to convert your font to `.woff` file with good render?

Thank you.

**Comment by vijender755** [comment]
Download .otf version from here -
https://www.indiantypefoundry.com/fonts/poppins
