### ISSUE TITLE
Rupee symbol report on fonts.google.com

### ISSUE THREAD

**Issue by chrissimpkins** [itfoundry/Poppins#58]
We received an anonymous user report through our front end site:

Currently, we are using the Poppins font in one of our mobile application and it works really well. But recenly we are facing an issue with the Indian Rupee symbol.

The Indian Rupee Symbol is ₹ but the poppins font is converting its bottom part to semi circular curve, which is not right as this is a specific symbol.

Can you pleas help us to make sure that the original Indian Ruppee symbol looks as is with Poppins font?

**Comment by jonpinhorn** [comment]
Hi Chris,

IMO, the shaping of the rupee symbol is subjective, just like all other
currency symbols, and 99% of all glyphs. Within the framing of what makes a
letter recognisable, at least.

**Comment by chrissimpkins** [comment]
No problem at all from our standpoint.  Just passing it along in case it is helpful feedback.
